aws-region: "us-east-2"
cognito-pool-id: "us-east-2_CEDW1OT68"

server:
  port: 8000

spring.security.oauth2.resourceserver.jwt:
  issuer-uri: https://cognito-idp.${aws-region}.amazonaws.com/${cognito-pool-id}


#debug: true
#logging:
#  level:
#    org.springframework.security: debug